package orm.sample;

import lombok.Data;
import orm.annotation.AutoGenerated;
import orm.annotation.Id;
import orm.annotation.ManyToOne;
import orm.annotation.Table;

@Table("logs")
@Data
public class LogEntity {

    @Id
    @AutoGenerated
    private Long id;

    private String entry;

    @ManyToOne
    private UserEntity user;
}
