package orm.sample;

import lombok.Data;
import orm.annotation.AutoGenerated;
import orm.annotation.Id;
import orm.annotation.OneToMany;
import orm.annotation.Table;

import java.util.List;

@Table("user_entity")
@Data
public class UserEntity {

    @Id
    @AutoGenerated
    private Long id;

    private String firstname;

    private String lastname;

    private Integer age;

    @OneToMany
    private List<LogEntity> logs;
}
