package orm.sample;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import orm.annotation.AutoGenerated;
import orm.annotation.Id;
import orm.annotation.OneToMany;
import orm.annotation.Table;

import java.util.List;
import java.util.Optional;

@Table("user_entity")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "logs")
@EqualsAndHashCode
@Builder
public class UserEntity {

    @Id
    @AutoGenerated
    private Long id;

    private String firstname;

    private String lastname;

    private Integer age;

    @OneToMany(foreignKeyName = "user_id")
    private List<LogEntity> logs;
}
